"""
barangay_init.py

Converts barangay_agents.csv into generative_agents persona bootstrap files.
Run from reverie/backend_server/:

  python barangay_init.py [--roles all|key] [--csv PATH] [--sim NAME]

--roles key  (default) initializes only political & enforcement agents (~30-50)
--roles all  initializes all 2,716 agents (slow; run after Qwen is verified)

Each agent also gets a Markdown file in personas/{name}.md containing their
personality text in human-readable form. Edit the MD to tune a persona — on
the next barangay_init.py run the MD values override the CSV-derived defaults.
"""
import csv
import json
import os
import re
import argparse

# Embedding via remote nomic-ai endpoint (matches gpt_structure.py get_embedding).
import os as _os
from openai import OpenAI as _OpenAI
_embed_client = _OpenAI(
    api_key="ollama",
    base_url=f"{_os.environ.get('EMBEDDING_ENDPOINT', 'http://10.158.24.216:8002')}/v1"
)
_embed_model_name = _os.environ.get("EMBEDDING_MODEL", "nomic-ai/nomic-embed-text-v1.5")

def _embed(text):
    text = text.replace("\n", " ") or "this is blank"
    try:
        return _embed_client.embeddings.create(
            input=[text], model=_embed_model_name
        ).data[0].embedding
    except Exception:
        # Embedding endpoint unavailable — use zero vector matching nomic's 768 dims.
        # Trust memories will still exist but won't be retrieved by semantic search.
        return [0.0] * 768

# ---------------------------------------------------------------------------
# Paths (relative to reverie/backend_server/)
# ---------------------------------------------------------------------------
STORAGE_ROOT = "../../environment/frontend_server/storage"
DEFAULT_CSV   = "../../../barangay_agents_qc_1000_final-1.csv"  # root of 197 repo
PERSONAS_DIR  = "personas"                       # editable MD files live here

# ---------------------------------------------------------------------------
# World definition (generated from the Barangay Mabuhay Tiled map).
# Contains the spatial-memory tree, per-sector walkable spawn tiles, and the
# CSV-zone-code -> "Sector:Arena" mapping. Generated by the map pipeline; all
# values are guaranteed to resolve against barangay_mabuhay/matrix.
# ---------------------------------------------------------------------------
_WORLD_JSON = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                           "barangay_mabuhay_world.json")
with open(_WORLD_JSON, encoding="utf-8") as _wf:
    _WORLD = json.load(_wf)

WORLD_NAME   = _WORLD["world_name"]          # "Barangay Mabuhay"
MAZE_NAME    = _WORLD["maze_name"]           # "barangay_mabuhay"
SPATIAL_TREE = _WORLD["spatial_tree"]        # {world: {sector: {arena: [objects]}}}
SECTOR_SPAWN = _WORLD["sector_spawn"]        # sector name -> [x, y] walkable tile
ZONE_TO_ADDR = _WORLD["zone_map"]            # csv zone code -> "Sector:Arena"
# sector name -> [[x,y], ...] pool of walkable tiles in the connected region.
# Each agent gets a DISTINCT tile so they don't all stack on one spot (stacking
# causes perpetual agent-to-agent conversation and zero movement).
SECTOR_SPAWN_POOL = _WORLD.get("sector_spawn_pool", {})

# ---------------------------------------------------------------------------
# Roles that count as "key" (political + enforcement) for --roles key
# ---------------------------------------------------------------------------
KEY_ROLES = {
    # Elected / appointed officials
    "mayor", "vice_mayor", "councilor",
    "barangay_captain", "barangay_kagawad",
    "barangay_treasurer", "barangay_secretary",
    # Municipal offices (budget, procurement, infrastructure)
    "municipal_engineer", "municipal_budget_officer", "municipal_treasurer",
    "procurement_officer", "business_permit_officer",
    # Oversight & accountability
    "coa_auditor", "local_journalist", "cso_organizer", "social_welfare_officer",
    # Enforcement
    "police_officer",
    # Dynasty / corruption-adjacent
    "local_elite_political_patron", "contractor_owner", "lawyer",
    "disaster_officer",
    # Corruption-orbit: civil servants pressured by officials
    "civil_servant_admin", "clerk_office_worker",
    # Corruption-orbit: business people paying bribes for permits/extortion
    "business_owner", "market_stall_owner", "market_vendor", "sari_sari_store_owner",
    "private_sector_manager",
    # Corruption-orbit: construction chain under corrupt contractors
    "site_supervisor", "subcontractor",
    # Corruption-orbit: professionals dependent on government budget allocation
    "doctor", "urban_health_nurse", "teacher",
}

# ---------------------------------------------------------------------------
# Role → daily schedule summary
# ---------------------------------------------------------------------------
ROLE_SCHEDULE = {
    # Political officials
    "mayor":                        "goes to Municipal Hall by 8am, holds meetings and signs documents until 5pm, attends evening community events occasionally.",
    "vice_mayor":                   "arrives at Municipal Hall by 8am, assists the mayor and chairs council sessions until 5pm.",
    "councilor":                    "attends Barangay Hall sessions at 9am, conducts community consultations, and returns home by 6pm.",
    "barangay_captain":             "opens Barangay Hall at 7am, mediates disputes, oversees programs, and closes by 7pm.",
    "barangay_kagawad":             "attends Barangay Hall by 8am, joins committee sessions and assists constituents until 5pm.",
    "barangay_treasurer":           "manages barangay funds at Barangay Hall from 8am to 5pm, reviews financial reports.",
    "barangay_secretary":           "handles records and correspondence at Barangay Hall from 8am to 5pm.",
    "local_elite_political_patron": "hosts meetings at home in the morning, visits key officials and allies throughout the day.",
    # Municipal offices
    "municipal_engineer":           "reviews infrastructure projects at Municipal Hall by 8am, conducts site inspections afternoons.",
    "municipal_budget_officer":     "prepares and monitors budget allocations at Municipal Hall from 8am to 5pm.",
    "municipal_treasurer":          "manages municipal accounts at Municipal Hall from 8am to 5pm.",
    "procurement_officer":          "processes procurement documents at Municipal Hall from 8am to 5pm.",
    "business_permit_officer":      "processes permits at Municipal Hall from 8am to 5pm.",
    "disaster_officer":             "coordinates disaster preparedness at Municipal Hall, conducts community drills.",
    # Oversight
    "coa_auditor":                  "arrives at the Audit Office by 8am, reviews financial records and conducts inspections until 5pm.",
    "local_journalist":             "works at the Media Office mornings, covers community events and investigates stories afternoons.",
    "cso_organizer":                "coordinates with community groups at the plaza and barangay hall throughout the day.",
    "social_welfare_officer":       "assists beneficiaries at Barangay Hall from 8am, conducts home visits afternoons.",
    # Enforcement
    "police_officer":               "reports to the Police Station at 6am, patrols the barangay, and ends shift at 6pm.",
    # Professionals
    "lawyer":                       "consults clients at the Contractor Office or home by 9am, attends hearings afternoons.",
    "doctor":                       "sees patients at the Health Center from 8am to 5pm.",
    "urban_health_nurse":           "reports to the Health Center at 7am, attends to patients until 4pm.",
    "teacher":                      "arrives at School by 7am, teaches classes until 3pm.",
    # Business / commerce
    "contractor_owner":             "visits the Contractor Office at 8am, inspects project sites throughout the day.",
    "business_owner":               "opens shop at the Public Market by 8am and manages business until 7pm.",
    "market_stall_owner":           "opens stall at the Public Market by 6am, sells goods until evening.",
    "market_vendor":                "sets up at the Public Market by 6am, sells goods until early evening.",
    "sari_sari_store_owner":        "opens the store at home by 6am, serves customers throughout the day.",
    "private_sector_manager":       "arrives at the office by 8am, manages operations and staff until 5pm.",
    "property_owner_retiree":       "tends to property matters in the morning, relaxes at the plaza afternoons.",
    # Workers
    "civil_servant_admin":          "arrives at the office by 8am, handles administrative tasks until 5pm.",
    "clerk_office_worker":          "reports to the office by 8am, processes documents until 5pm.",
    "construction_worker":          "reports to the construction site by 7am, works until 4pm.",
    "skilled_tradesperson":         "takes jobs around the barangay, works from early morning to late afternoon.",
    "factory_plant_worker":         "reports to the factory by 6am, works an 8-hour shift.",
    "site_supervisor":              "inspects construction sites from 7am, coordinates workers throughout the day.",
    "subcontractor":                "manages subcontract work on construction sites from 7am to 5pm.",
    # Agriculture
    "farmer":                       "wakes at 5am, works in the farm field all morning, returns home by noon.",
    "fisherman":                    "leaves for fishing at 4am, returns by mid-morning, maintains equipment afternoons.",
    # Community
    "home_caregiver":               "tends to family and household from early morning, occasionally visits neighbors.",
    "unemployed_jobseeker":         "wakes late, spends time at the plaza or market looking for work opportunities.",
    "elder_retiree":                "wakes early, visits the church in the morning, rests at the plaza in the afternoon.",
    "student":                      "attends school from 7am to 3pm, studies at home in the evenings.",
}

# ---------------------------------------------------------------------------
# Trait → adjective mapping for building personality description
# ---------------------------------------------------------------------------
def trait_adjectives(row):
    """Convert numeric trait scores into descriptive adjectives for innate field."""
    parts = []

    def level(val, low="low", mid="moderate", high="high"):
        v = float(val)
        if v >= 0.7: return high
        if v >= 0.4: return mid
        return low

    integrity = float(row["integrity"])
    greed     = float(row["greed"])
    ambition  = float(row["ambition"])
    empathy   = float(row["empathy"])
    competence= float(row["competence"])
    family_loyalty = float(row["family_loyalty"])

    if integrity >= 0.7:   parts.append("honest")
    elif integrity < 0.35: parts.append("dishonest")

    if greed >= 0.7:       parts.append("greedy")
    elif greed < 0.35:     parts.append("selfless")

    if ambition >= 0.7:    parts.append("ambitious")
    elif ambition < 0.35:  parts.append("content")

    if empathy >= 0.7:     parts.append("empathetic")
    elif empathy < 0.35:   parts.append("callous")

    if competence >= 0.7:  parts.append("highly competent")
    elif competence < 0.35:parts.append("inexperienced")

    if family_loyalty >= 0.7: parts.append("deeply loyal to family")

    return ", ".join(parts) if parts else "ordinary"


# ---------------------------------------------------------------------------
# Persona MD helpers
# ---------------------------------------------------------------------------

# The five text fields that flow from MD → scratch.json
_MD_SECTIONS = {
    "Personality":    "innate",
    "Background":     "learned",
    "Current Goals":  "currently",
    "Daily Routine":  "lifestyle",
    "Daily Plan":     "daily_plan_req",
}


def write_persona_md(md_path, scratch, row):
    """Write a human-readable personality file for one agent."""
    name      = scratch["name"]
    role      = row["role"].replace("_", " ")
    family_id = row.get("family_id", "").strip() or "none"

    lines = [
        f"# {name}",
        "",
        f"**Role:** {role} | **Age:** {scratch['age']} | "
        f"**Social Class:** {row['social_class']} | **Family:** {family_id}",
        "",
        "---",
        "",
    ]
    for section, key in _MD_SECTIONS.items():
        lines += [f"## {section}", scratch[key], ""]

    # Dynamism-relevant numeric attributes, round-tripped via persona_md so they
    # can be hand-edited mid-run to steer corruption/election/news.
    lines += ["## Attributes"]
    for k in ("greed", "integrity", "ambition", "family_loyalty",
              "satisfaction", "initial_trust_score"):
        if row.get(k) not in (None, ""):
            lines += [f"- {k}: {row[k]}"]
    lines += [""]

    with open(md_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def read_persona_md(md_path):
    """Parse text fields from an existing persona MD file.
    Returns a dict of {scratch_key: text} for fields found in the file.
    Only the five personality sections are extracted; everything else is ignored.
    """
    with open(md_path, encoding="utf-8") as f:
        content = f.read()

    overrides = {}
    for section, key in _MD_SECTIONS.items():
        match = re.search(rf'## {re.escape(section)}\s*\n(.*?)(?=\n##|\Z)',
                          content, re.DOTALL)
        if match:
            text = match.group(1).strip()
            if text:
                overrides[key] = text
    return overrides


def make_scratch(row):
    name = row["name"].strip()
    parts = name.split()
    first = parts[0]
    last  = " ".join(parts[1:]) if len(parts) > 1 else ""

    role       = row["role"].replace("_", " ")
    social     = row["social_class"]
    age        = int(row["age"])
    edu        = int(row["education_level"])
    goals_raw  = row.get("goals", "").strip()
    goals_list = [g.strip() for g in goals_raw.split("|") if g.strip()]
    goals_str  = "; ".join(goals_list[:3]) if goals_list else "live a decent life"
    family_id  = row.get("family_id", "").strip() or None
    home_zone  = row.get("home_zone", "resA")
    work_zone  = row.get("work_zone", "park")
    satisfaction = float(row.get("satisfaction", 50))

    innate  = trait_adjectives(row)
    edu_desc = ["uneducated", "elementary graduate", "high school student",
                "high school graduate", "college graduate", "post-graduate"][min(edu, 5)]

    learned = (
        f"{name} is a {role} in {WORLD_NAME}, {social} class, {age} years old, "
        f"{edu_desc}. "
    )
    if family_id:
        learned += f"They belong to the {family_id} political family. "
    learned += (
        f"They earn {float(row['income_per_day']):.0f} pesos per day and have "
        f"accumulated {float(row['wealth']):.0f} pesos in wealth. "
        f"Their satisfaction with life is currently {satisfaction:.0f}/100."
    )

    currently = f"{name} is focused on: {goals_str}."

    schedule_text = ROLE_SCHEDULE.get(row["role"],
        "follows a typical daily routine based on their role and responsibilities.")
    lifestyle = f"{name} wakes up around 6am, {schedule_text} Goes to bed around 10pm."

    home_sub = ZONE_TO_ADDR.get(home_zone, ZONE_TO_ADDR["resA"])
    home_address = f"{WORLD_NAME}:{home_sub}"

    daily_plan = (
        f"{name} works as a {role} in {WORLD_NAME}. "
        + ROLE_SCHEDULE.get(row["role"], "Follows a standard daily routine.")
    )

    return {
        "vision_r": 8,
        "att_bandwidth": 8,
        "retention": 8,
        "curr_time": None,
        "curr_tile": None,
        "daily_plan_req": daily_plan,
        "name": name,
        "first_name": first,
        "last_name": last,
        "age": age,
        "innate": innate,
        "learned": learned,
        "currently": currently,
        "lifestyle": lifestyle,
        "living_area": home_address,
        "concept_forget": 100,
        "daily_reflection_time": 180,
        "daily_reflection_size": 5,
        "overlap_reflect_th": 4,
        "kw_strg_event_reflect_th": 10,
        "kw_strg_thought_reflect_th": 9,
        "recency_w": 1,
        "relevance_w": 1,
        "importance_w": 1,
        "recency_decay": 0.995,
        "importance_trigger_max": 150 if row["role"] in KEY_ROLES else 300,
        "importance_trigger_curr": 150 if row["role"] in KEY_ROLES else 300,
        "importance_ele_n": 0,
        "thought_count": 5 if row["role"] in KEY_ROLES else 3,
        "agent_tier": 1 if row["role"] in KEY_ROLES else 2,
        # Tier-2 probabilistic reflection: competence (0-1) → 1-10% chance per trigger
        # Weekly cooldown tracked via last_reflect_time (game-time datetime string)
        "reflect_prob": round(float(row.get("competence", 0.5)) * 0.1, 4),
        "last_reflect_time": None,
        "role": row["role"],
        "daily_req": [],
        "f_daily_schedule": [],
        "f_daily_schedule_hourly_org": [],
        "act_address": None,
        "act_start_time": None,
        "act_duration": None,
        "act_description": None,
        "act_pronunciatio": None,
        "act_event": [name, None, None],
        "act_obj_description": None,
        "act_obj_pronunciatio": None,
        "act_obj_event": [None, None, None],
        "chatting_with": None,
        "chat": None,
        "chatting_with_buffer": {},
        "chatting_end_time": None,
        "act_path_set": False,
        "planned_path": [],
    }


def make_spatial_memory():
    """Return the full Barangay Mabuhay spatial tree (generated from the map)."""
    import copy
    return copy.deepcopy(SPATIAL_TREE)


def make_empty_associative_memory():
    return {"nodes": {}, "seq_event": [], "seq_thought": [], "seq_chat": []}


def write_persona(name, scratch, spatial, assoc_mem, storage_root, sim_name):
    persona_dir = os.path.join(storage_root, sim_name, "personas", name, "bootstrap_memory")
    assoc_dir   = os.path.join(persona_dir, "associative_memory")
    os.makedirs(assoc_dir, exist_ok=True)

    with open(os.path.join(persona_dir, "scratch.json"), "w") as f:
        json.dump(scratch, f, indent=2)

    with open(os.path.join(persona_dir, "spatial_memory.json"), "w") as f:
        json.dump(spatial, f, indent=2)

    with open(os.path.join(assoc_dir, "nodes.json"), "w") as f:
        json.dump({}, f)

    with open(os.path.join(assoc_dir, "embeddings.json"), "w") as f:
        json.dump({}, f)

    with open(os.path.join(assoc_dir, "kw_strength.json"), "w") as f:
        json.dump({"kw_strength_event": {}, "kw_strength_thought": {}}, f)


def write_meta(storage_root, sim_name, agent_names):
    """Write the sim meta.json listing all persona names."""
    meta_dir = os.path.join(storage_root, sim_name)
    os.makedirs(meta_dir, exist_ok=True)
    meta = {
        "curr_time": "February 13, 2024, 07:00:00",
        "sec_per_step": 3600,
        "maze_name": "barangay",
        "persona_names": agent_names,
        "step": 0,
    }
    with open(os.path.join(meta_dir, "reverie", "meta.json"), "w") as f:
        json.dump(meta, f, indent=2)
    # Also write movement placeholder
    move_dir = os.path.join(meta_dir, "movement")
    os.makedirs(move_dir, exist_ok=True)
    with open(os.path.join(move_dir, "0.json"), "w") as f:
        json.dump({"persona": {}, "meta": {"curr_time": "February 13, 2024, 07:00:00"}}, f)


def seed_family_trust_memories(agent_rows, storage_root, sim_name):
    """
    Pre-seed each agent's associative memory with trust thoughts for their
    family members (same family_id).  These thoughts have high poignancy (8)
    so they surface early in the sim and bias interactions toward family allies.
    """
    # Group agent names by family_id (skip agents with no family_id).
    family_groups = {}
    for row in agent_rows:
        fid = row.get("family_id", "").strip()
        if fid:
            family_groups.setdefault(fid, []).append(row["name"].strip())

    if not family_groups:
        print("  No family groups found — skipping trust seeding.")
        return

    CREATED = "2024-02-13 07:00:00"
    seeded = 0

    for row in agent_rows:
        name = row["name"].strip()
        fid = row.get("family_id", "").strip()
        if not fid:
            continue
        family_members = [m for m in family_groups[fid] if m != name]
        if not family_members:
            continue

        assoc_dir = os.path.join(storage_root, sim_name, "personas", name,
                                 "bootstrap_memory", "associative_memory")
        nodes_path = os.path.join(assoc_dir, "nodes.json")
        embed_path = os.path.join(assoc_dir, "embeddings.json")
        if not os.path.exists(nodes_path):
            continue  # persona wasn't initialised (filtered by --roles key)

        with open(nodes_path) as f:
            nodes = json.load(f)
        with open(embed_path) as f:
            embeddings = json.load(f)

        # Find the next sequential node/thought count.
        node_offset = len(nodes)
        thought_offset = sum(1 for n in nodes.values() if n["type"] == "thought")

        for idx, other in enumerate(family_members):
            desc = f"{name} trusts {other} because they are family"
            node_num = node_offset + idx + 1
            thought_num = thought_offset + idx + 1
            nodes[f"node_{node_num}"] = {
                "node_count": node_num,
                "type_count": thought_num,
                "type": "thought",
                "depth": 1,
                "created": CREATED,
                "expiration": None,
                "subject": name,
                "predicate": "trusts",
                "object": other,
                "description": desc,
                "embedding_key": desc,
                "poignancy": 8,
                "keywords": ["family", "trust", other.lower()],
                "filling": [],
            }
            embeddings[desc] = _embed(desc)

        with open(nodes_path, "w") as f:
            json.dump(nodes, f, indent=2)
        with open(embed_path, "w") as f:
            json.dump(embeddings, f)

        seeded += len(family_members)

    print(f"  Family trust: seeded {seeded} trust memories across {len(family_groups)} families.")


def main():
    parser = argparse.ArgumentParser(description="Initialize barangay personas")
    parser.add_argument("--roles", choices=["key", "all"], default="key",
                        help="'key' = political+enforcement only; 'all' = full 2716 agents")
    parser.add_argument("--total", type=int, default=None,
                        help="Cap total agents at N: always writes all KEY_ROLES first, "
                             "then fills with Tier-2 agents up to N")
    parser.add_argument("--csv", default=DEFAULT_CSV, help="Path to barangay_agents.csv")
    parser.add_argument("--sim", default="base_barangay", help="Simulation storage name")
    parser.add_argument("--personas-dir", default=None,
                        help="Directory for persona MD files (default: personas/ next to this script)")
    args = parser.parse_args()

    csv_path = os.path.abspath(os.path.join(os.path.dirname(__file__), args.csv))
    storage_root = os.path.abspath(os.path.join(os.path.dirname(__file__), STORAGE_ROOT))
    personas_dir = os.path.abspath(
        args.personas_dir if args.personas_dir
        else os.path.join(os.path.dirname(__file__), PERSONAS_DIR)
    )
    os.makedirs(personas_dir, exist_ok=True)

    print(f"Reading agents from: {csv_path}")
    print(f"Writing to:          {storage_root}/{args.sim}")
    print(f"Persona MD files:    {personas_dir}")

    spatial = make_spatial_memory()
    agent_names = []
    agent_work_zones = {}
    agent_home_zones = {}
    skipped = 0
    md_loaded = 0
    md_created = 0

    # Read all rows up front so we can pass them to seed_family_trust_memories
    # (family members may span key and non-key roles).
    with open(csv_path, newline="", encoding="utf-8") as f:
        all_rows = list(csv.DictReader(f))

    # Split rows into Tier-1 (key roles) and Tier-2 (everyone else).
    tier1_rows = [r for r in all_rows if r["role"] in KEY_ROLES]
    tier2_rows = [r for r in all_rows if r["role"] not in KEY_ROLES]

    # Decide which rows to write based on --roles and --total.
    if args.total is not None:
        fill = max(0, args.total - len(tier1_rows))
        rows_to_write = tier1_rows + tier2_rows[:fill]
        print(f"--total {args.total}: {len(tier1_rows)} Tier-1 (key) + {min(fill, len(tier2_rows))} Tier-2 agents")
    elif args.roles == "key":
        rows_to_write = tier1_rows
    else:
        rows_to_write = all_rows

    for row in rows_to_write:
            name = row["name"].strip()
            scratch = make_scratch(row)

            # MD is the authoritative personality source once it exists.
            md_path = os.path.join(personas_dir, f"{name}.md")
            if os.path.exists(md_path):
                overrides = read_persona_md(md_path)
                scratch.update(overrides)
                md_loaded += 1
            else:
                write_persona_md(md_path, scratch, row)
                md_created += 1

            assoc = make_empty_associative_memory()
            write_persona(name, scratch, spatial, assoc, storage_root, args.sim)
            agent_names.append(name)
            agent_work_zones[name] = row.get("work_zone", "resA").strip()
            agent_home_zones[name] = row.get("home_zone", "resA").strip()

    # Write reverie meta
    reverie_meta_dir = os.path.join(storage_root, args.sim, "reverie")
    os.makedirs(reverie_meta_dir, exist_ok=True)
    meta = {
        "curr_time": "February 13, 2024, 07:00:00",
        "start_date": "February 13, 2024",
        "sec_per_step": 3600,
        "maze_name": MAZE_NAME,
        "persona_names": agent_names,
        "step": 0,
    }
    with open(os.path.join(reverie_meta_dir, "meta.json"), "w") as f:
        json.dump(meta, f, indent=2)

    # NOTE: do NOT pre-write movement/0.json. headless_env.py would consume the
    # placeholder instantly and write env/1 from it before reverie computes the
    # real step 0, freezing every agent at [0,0]. reverie writes the real
    # movement/0.json itself after step 0; headless_env waits for it.
    move_dir = os.path.join(storage_root, args.sim, "movement")
    os.makedirs(move_dir, exist_ok=True)

    # Write initial tile positions for each persona (required by reverie.py)
    env_dir = os.path.join(storage_root, args.sim, "environment")
    os.makedirs(env_dir, exist_ok=True)
    env_positions = {}
    _fallback = next(iter(SECTOR_SPAWN.values()))
    _pool_idx = {}
    _pool_warned = set()
    for name in agent_names:
        hz = agent_home_zones.get(name, "resA")
        sector = ZONE_TO_ADDR.get(hz, ZONE_TO_ADDR["resA"]).split(":")[0]
        pool = SECTOR_SPAWN_POOL.get(sector)
        if pool:
            k = _pool_idx.get(sector, 0)
            if k >= len(pool):
                if sector not in _pool_warned:
                    print(f"  WARNING: spawn pool for '{sector}' exhausted "
                          f"({len(pool)} tiles, {k+1}+ agents). "
                          f"Expand sector_spawn_pool in the world JSON.")
                    _pool_warned.add(sector)
                xy = pool[-1]  # clamp to last tile rather than cycling
            else:
                xy = pool[k]
            _pool_idx[sector] = k + 1
        else:
            xy = SECTOR_SPAWN.get(sector, _fallback)
        env_positions[name] = {"x": xy[0], "y": xy[1]}
    with open(os.path.join(env_dir, "0.json"), "w") as f:
        json.dump(env_positions, f, indent=2)

    # Pre-seed family trust memories using all rows (family members may not all
    # be in the key-roles subset, but the function skips missing persona dirs).
    seed_family_trust_memories(all_rows, storage_root, args.sim)

    n_t1 = sum(1 for n in agent_names
               if any(r["name"].strip() == n and r["role"] in KEY_ROLES for r in rows_to_write))
    n_t2 = len(agent_names) - n_t1
    print(f"\nInitialized {len(agent_names)} personas  "
          f"(Tier-1: {n_t1}, Tier-2: {n_t2}).")
    print(f"  MD files: {md_created} created, {md_loaded} loaded from existing.")
    print(f"  Edit {personas_dir}/<name>.md to tune a persona, then re-run to update JSON.")
    if args.total is None and args.roles == "key":
        print("Tip: --total 100 to add Tier-2 fill agents; --roles all for full 2716.")


if __name__ == "__main__":
    main()
